# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - accessgrant

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Build project'
        shell: pwsh
        run: |
          pushd './server'
          npm install
          npm run build --if-present
          npm prune --production
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_297382C1C6954A9AA8F63B7F55A556F1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45FE9608540B4EC6B2FACE88E66A3FE9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_63CA12F55301451F92FE5D0A25CE2E7F }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'accessgrant'
          slot-name: 'Production'
          package: server
